#!/bin/bash

. common

test_init $(basename "$0")

# Expected output
app_regex=(
  'T:\s*\d+\s*\(\s*\d+\)\s*P:80\s*I:200\s*C:\s*\d+\s*Min:\s*\d+\s*Act:\s*\d+\s*Avg:\s*\d+\s*Max:\s*\d+'
)

catch cyclictest --mlockall --smp --priority=80 --interval=200 --distance=0 --quiet --loops=10

app_exit_check $?

check_output || test_failed

app_regex=(
  'T:\s*\d+\s*\(\s*\d+\)\s*P:80\s*I:\d+\s*C:\s*\d+\s*Min:\s*\d+\s*Act:\s*\d+\s*Avg:\s*\d+\s*Max:\s*\d+'
)

catch cyclictest --mlockall --smp --priority=80 --interval=20 --loops=1000

app_exit_check $?

check_output || test_failed

test_success
