#!/bin/bash

. common

test_init $(basename "$0")

catch hackbench --datasize=512 --groups=15 --loops=200 --fds=25 --pipe

app_exit_check $?

msg='Running in process mode with 15 groups using 50 file descriptors each \(== 750 tasks\)'
# Check program output behavior
app_regex=(
	$msg \
	'Each sender will pass 200 messages of 512 bytes' \
	'Time: \d+.\d+'
	)

check_output || test_failed

test_success
