#!/bin/bash

. common

test_init $(basename "$0")

catch rt-migrate-test --loops=50 --quiet

app_exit_check $?

# Check program output behavior
app_regex=(
	'Parent pid: \d+' \
	'Task \d+ \(prio \d+\) \(pid \d+\):'
	'Max: \d+ us' \
	'Min: \d+ us' \
	'Tot: \d+ us' \
	'Avg: \d+ us'
	)

check_output || test_failed

test_success
