#!/bin/bash

. common

test_init $(basename "$0")

catch pmqtest --loops=10 --prio=80 --threads --quiet 

app_exit_check $?

# Check program output behavior
app_regex=(
	'#\d+:\s*ID\d+,\s*P\d+,\s*CPU\d+,\s*I\d+;\s*#\d+:\s*ID\d+,\s*P\d+,\s*CPU\d+,\s*TO\s\d+,\s*Cycles\s*\d+' \
	)

check_output || test_failed

test_success
