#!/bin/bash

. common

test_init $(basename "$0")

catch queuelat --cycles 100 --max-len 10000 --packets 1 --freq 10 

app_exit_check $?

# Check program output behavior
app_regex=(
	'tsc_freq_ghz = \d+.\d+, cycles_to_ns = \d+.\d+' \
	'max_queue_len = 1'
	)

check_output || test_failed

test_success
