#!/bin/bash

. common

test_init $(basename "$0")

catch ssdd --iters=10 --quiet

app_exit_check $?

# Check program output behavior
app_regex=(
	'All tests PASSED.'
)

check_output || test_failed

test_success
