#!/bin/bash

. common

test_init $(basename "$0")

catch svsematest --threads=$(nproc) --smp --prio=80  --loops=10 

app_exit_check $?

# Check program output behavior
app_regex=(
	'#\d+:\s*ID\d+,\s*P80,\s*CPU\d+,\s*I\d+;\s*#\d+:\sID\d+,\sP80,\s*CPU\d+,\s*Cycles\s*\d+' \
	'#\d+\s*->\s*#\d+.\s*Min\s*\d+,\s*Cur\s*\d+,\s*Avg\s*\d+,\s*Max\s*\d+'
	)

check_output || test_failed

test_success
