#!/bin/bash

. common

test_init $(basename "$0")

catch signaltest --loops=10 --threads=$(nproc) --quiet 

app_exit_check $?

# Check program output behavior
app_regex=(
	'T:\s*\d+\s*\(\s*\d+\s*\)\s*P:\s*\d+\s*C:\s*\d+\s*Min:\s*\d+\s*Act:\s*\d+\s*Avg:\s*\d+\s*Max:\s*\d+'
	)

check_output || test_failed

test_success

