name: rt-tests
base: core24
version: nil
summary: Real-time test suite
description: |
  rt-tests is a set of programs to test various real time Linux features. 
  
  The programs include: 
  cyclicdeadline, cyclictest, deadline_test, hackbench, hwlatdetect, oslat, pi_stress, pip_stress, pmqtest,
  ptsematest, queuelat, rt-migrate-test, signaltest, sigwaittest, ssdd, svsematest.

  For usage instructions, refer to:  https://github.com/canonical/rt-tests-snap

license: GPL-2.0-or-later AND LGPL-2.1-or-later
grade: stable
confinement: strict
adopt-info: version

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

slots:
  rt-tests-posix-mq:
    interface: posix-mq
    path:
      - /syncmsg
      - /testmsg
    permissions:
      - read

plugs:
  sys-kernel-debug-sched-features:
    interface: system-files
    write:
      - /sys/kernel/debug/sched/features
  shared-memory:
    private: true

parts:

  version:
    plugin: nil
    source: .
    override-build: |
      craftctl set version=2.7+$(git rev-parse --short HEAD)
  
  deb-patches:
    plugin: nil
    source: https://git.launchpad.net/ubuntu/+source/rt-tests
    source-depth: 1
    source-branch: ubuntu/devel
    source-type: git
    override-build: |
      cp debian/patches/*.patch $CRAFT_STAGE

  patches:
    plugin: nil
    source: patches
    override-build: |
      cp *.patch $CRAFT_STAGE

  realtime-tests:
      after:
        - patches
      plugin: make
      source: https://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
      source-tag: v2.7
      source-depth: 1
      build-packages:
          - git
          - build-essential
          - libnuma-dev
          - python3
          - tree
      stage-packages:
          - libnuma1
      prime:
          - usr/bin/cyclicdeadline
          - usr/bin/cyclictest
          - usr/bin/deadline_test
          - usr/sbin/get-cyclictest-snapshot
          - usr/bin/hackbech
          - usr/sbin/hwlatdetect
          - usr/bin/pip_stress
          - usr/bin/pi_stress
          - usr/bin/pmqtest
          - usr/bin/ptsematest
          - usr/bin/rt-migrate-test
          - usr/bin/signaltest
          - usr/bin/sigwaittest
          - usr/bin/svsematest
          - usr/bin/ssdd
          - usr/bin/oslat
          - usr/bin/queuelat
          - usr/lib/**/libnuma*
      override-build: |

        # git apply $CRAFT_STAGE/*.patch
        ls $CRAFT_STAGE/*.patch | xargs -n 1 git apply

        craftctl default

apps:

  cyclicdeadline:
    command: usr/bin/cyclicdeadline
    plugs: [ mount-observe, system-trace ]

  cyclictest:
    command: usr/bin/cyclictest
    plugs: [ process-control, shared-memory ]

  deadline-test:
    command: usr/bin/deadline_test
    plugs: [ process-control, mount-observe, system-trace, sys-kernel-debug-sched-features ]

  hackbench:
    command: usr/bin/hackbench

  oslat:
    command: usr/bin/oslat

  pi-stress:
    command: usr/bin/pi_stress
    plugs: [ process-control ]

  pip-stress:
    command: usr/bin/pip_stress
    plugs: [ process-control ]

  pmqtest:
    command: usr/bin/pmqtest
    slots: [ rt-tests-posix-mq ]
    plugs: [ process-control ]

  ptsematest:
    command: usr/bin/ptsematest
    plugs: [ process-control ]

  queuelat:
    command: usr/bin/queuelat

  rt-migrate-test:
    command: usr/bin/rt-migrate-test

  signaltest:
    command: usr/bin/signaltest
    plugs: [ process-control ]

  sigwaittest:
    command: usr/bin/sigwaittest
    plugs: [ process-control ]

  ssdd:
    command: usr/bin/ssdd

  svsematest:
    command: usr/bin/svsematest
    plugs: [ process-control ]

  hwlatdetect:
    command: usr/sbin/hwlatdetect
    plugs: [ mount-observe, system-trace ]

  get-cyclictest-snapshot:
    command: usr/sbin/get_cyclictest_snapshot

