name: real-time-tests 
base: core22 
version: '0.2' 
summary: Real time tests for UC22
description: |
  Based on Real Time Tests debian package rt-tests, maintened by Clark Williams
  and John Kacur. This snap is a collection of programs to test the
  real-time capabilities of the Linux kernel. Programs included: cyclicdeadline,
  cyclictest, deadline_test, hackbench, oslat, pi_stress, pip_stress, pmqtest,
  ptsematest, queuelat, rt-migrate-test, signaltest, sigwaittest, ssdd, svsematest.

license: GPL-2.0

architectures:
  - build-on: amd64

grade: stable
confinement: strict

parts:
  rt-tests:
    plugin: nil
    source-branch: main
    source: git://git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git
    build-packages:
      - gcc
      - make
      - python3
    stage-packages:
      - libnuma1

    override-build: |
      mkdir -p $CRAFT_PART_INSTALL/usr/local/bin
      DESTDIR=$CRAFT_PART_INSTALL make install

      rm $CRAFT_PART_INSTALL/usr/local/bin/hwlatdetect
      rm $CRAFT_PART_INSTALL/usr/local/bin/get_cyclictest_snapshot
      
apps:
  cyclicdeadline:
    command: usr/local/bin/cyclicdeadline
    plugs:
      - process-control
  
  cyclictest:
    command: usr/local/bin/cyclictest
    plugs:
      - process-control

  deadlinetest:
    command: usr/local/bin/deadline_test
    plugs:
      - process-control
  
  hackbench:
    command: usr/local/bin/hackbench
    plugs:
      - process-control

  oslat:
    command: usr/local/bin/oslat
    plugs:
      - process-control

  pi-stress:
    command: usr/local/bin/pi_stress
    plugs:
      - process-control

  pip-stress:
    command: usr/local/bin/pip_stress
    plugs:
      - process-control

  pmqtest:
    command: usr/local/bin/pmqtest
    plugs:
      - process-control
  
  ptsematest:
    command: usr/local/bin/ptsematest
    plugs:
      - process-control

  queuelat:
    command: usr/local/bin/queuelat
    plugs:
      - process-control

  rt-migrate-test:
    command: usr/local/bin/rt-migrate-test
    plugs:
      - process-control
  
  signaltest:
    command: usr/local/bin/signaltest
    plugs:
      - process-control
  
  sigwaittest:
    command: usr/local/bin/sigwaittest
    plugs:
      - process-control
  
  ssdd:
    command: usr/local/bin/ssdd
    plugs:
      - process-control
  
  svsematest:
    command: usr/local/bin/svsematest
    plugs:
      - process-control